name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

env:
  GOLANGCILINT_VERSION: "v1.50.1"

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build Go projects
        run: |
          ROOT_DIR=$(pwd)
          for directory in beginner/*
          do
            cd $directory
            go build -v
            cd $ROOT_DIR
          done
      # https://github.com/golangci/golangci-lint-action can't be used on several directories
      - name: Install Go linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCILINT_VERSION}
      - name: Lint Go projects
        run: |
          ROOT_DIR=$(pwd)
          for directory in beginner/*
          do
            cd $directory
            golangci-lint run -v
            cd $ROOT_DIR
          done
        # TODO: add tests
